version: '3.4'
networks:
  customerdemoapp:
services:
  demoappdb:
    container_name: "app_DB"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345# 
    networks:
      - customerdemoapp
  webapplication7:
    container_name: "Demo_Customer_App"
    image: ${DOCKER_REGISTRY-}webapplication7
    build:
      context: .
      dockerfile: WebApplication7/Dockerfile
    ports:
      - 8001:80
    depends_on: 
      - demoappdb
    environment:
     - DB_HOST=demoappdb
     - DB_NAME= CustomerDatabaseDocker
     - DB_MSSQL_SA_PASSWORD=password@12345#
    networks:
     - customerdemoapp
